services:
  - type: web
    name: my-re-tool-app
    env: python
    buildCommand: ""
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
